param location string = 'francecentral'
param containerAppName string = 'orbit-campaign-agrifica'
param resourceGroupName string = 'rg-orbit-campaign-agrifica'
param containerAppsEnvironmentName string = 'cae-orbit-platform'
param acrName string = 'crorbitplatform'
param imageTag string = 'latest'
param userAssignedIdentityName string = 'id-orbit-campaign-agrifica'
param storageAccountName string = 'stcampagrifica'
param keyVaultName string = 'kv-orbit-camp-agrifica'
param customHostname string = ''
resource cae 'Microsoft.App/managedEnvironments@2023-05-01' existing = { name: containerAppsEnvironmentName scope: resourceGroup(resourceGroupName) }
resource acr 'Microsoft.ContainerRegistry/registries@2023-07-01' existing = { name: acrName }
resource id 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = { name: userAssignedIdentityName location: location }
module storage 'storage.bicep' = { name: 'storage' params: { location: location storageAccountName: storageAccountName } }
module keyvault 'keyvault.bicep' = { name: 'keyvault' params: { location: location keyVaultName: keyVaultName tenantId: subscription().tenantId principalId: id.properties.principalId } }
resource acrPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = { name: guid(acr.id, id.properties.principalId, 'AcrPull') scope: acr properties: { principalId: id.properties.principalId principalType: 'ServicePrincipal' roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '7f951dda-4ed3-4680-a7ca-43fe172d538d') } }
resource app 'Microsoft.App/containerApps@2023-05-01' = { name: containerAppName location: location identity: { type: 'UserAssigned' userAssignedIdentities: { '${id.id}': {} } } properties: { managedEnvironmentId: cae.id configuration: { activeRevisionsMode: 'Single' ingress: { external: true targetPort: 8000 transport: 'auto' allowInsecure: false } registries: [{ server: '${acrName}.azurecr.io' identity: id.id }] secrets: [] } template: { containers: [{ name: 'runtime' image: '${acrName}.azurecr.io/${containerAppName}:${imageTag}' env: [ { name: 'CAMPAIGN_ID' value: 'ab5b944c-e9cb-4bf7-bd69-fbdca33a1aa1' } { name: 'SLUG' value: 'agrifica' } { name: 'STORAGE_TABLE_ENDPOINT' value: storage.outputs.tableEndpoint } { name: 'STORAGE_BLOB_ENDPOINT' value: storage.outputs.blobEndpoint } { name: 'KEY_VAULT_NAME' value: keyVaultName } ] resources: { cpu: json('0.5') memory: '1Gi' } }] scale: { minReplicas: 1 maxReplicas: 3 } } } dependsOn: [acrPull] }
output fqdn string = app.properties.configuration.ingress.fqdn
output identityId string = id.id
